apiVersion: storage.vastai.m.crossplane.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: dataset
  name: dataset
  namespace: crossplane-system
spec:
  forProvider:
    name: training-dataset
    offerId: ${data.vastai_volume_offers.storage.most_affordable.id}
    size: 100
