// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0


// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"

)




type VolumeInitParameters struct {


// (Number) Source volume ID to clone from. When set, creates by cloning (POST /volumes/copy/) instead of creating from offer. Changes force replacement.
// Source volume ID to clone from. When set, creates by cloning (POST /volumes/copy/) instead of creating from offer. Changes force replacement.
CloneFromID *float64 `json:"cloneFromId,omitempty" tf:"clone_from_id,omitempty"`

// (Boolean) Disable compression during clone. Only used when clone_from_id is set. Changes force replacement.
// Disable compression during clone. Only used when clone_from_id is set. Changes force replacement.
DisableCompression *bool `json:"disableCompression,omitempty" tf:"disable_compression,omitempty"`

// (String) Optional name/label for the volume. Changes force replacement.
// Optional name/label for the volume. Changes force replacement.
Name *string `json:"name,omitempty" tf:"name,omitempty"`

// time attribute not returned by the API; preserved in state via UseStateForUnknown.
// ID of the volume offer to create from (from vastai_volume_offers data source). When cloning, this is the destination offer ID. Changes force replacement. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
OfferID *float64 `json:"offerId,omitempty" tf:"offer_id,omitempty"`

// time attribute not returned by the API; preserved in state via UseStateForUnknown.
// Volume size in GB. Changes force replacement. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}


type VolumeObservation struct {


// (Number) Source volume ID to clone from. When set, creates by cloning (POST /volumes/copy/) instead of creating from offer. Changes force replacement.
// Source volume ID to clone from. When set, creates by cloning (POST /volumes/copy/) instead of creating from offer. Changes force replacement.
CloneFromID *float64 `json:"cloneFromId,omitempty" tf:"clone_from_id,omitempty"`

// (Boolean) Disable compression during clone. Only used when clone_from_id is set. Changes force replacement.
// Disable compression during clone. Only used when clone_from_id is set. Changes force replacement.
DisableCompression *bool `json:"disableCompression,omitempty" tf:"disable_compression,omitempty"`

// (String) Name of the physical disk hosting this volume.
// Name of the physical disk hosting this volume.
DiskName *string `json:"diskName,omitempty" tf:"disk_name,omitempty"`

// (Number) Actual allocated disk space in GB.
// Actual allocated disk space in GB.
DiskSpace *float64 `json:"diskSpace,omitempty" tf:"disk_space,omitempty"`

// (String) Driver version on the host machine.
// Driver version on the host machine.
DriverVersion *string `json:"driverVersion,omitempty" tf:"driver_version,omitempty"`

// (String) Geographic location of the machine hosting this volume.
// Geographic location of the machine hosting this volume.
Geolocation *string `json:"geolocation,omitempty" tf:"geolocation,omitempty"`

// (Number) ID of the host machine.
// ID of the host machine.
HostID *float64 `json:"hostId,omitempty" tf:"host_id,omitempty"`

// (String) Volume contract ID. Used as the primary identifier for reads, deletes, and imports.
ID *string `json:"id,omitempty" tf:"id,omitempty"`

// (Number) Internet download speed in Mbps.
// Internet download speed in Mbps.
InetDown *float64 `json:"inetDown,omitempty" tf:"inet_down,omitempty"`

// (Number) Internet upload speed in Mbps.
// Internet upload speed in Mbps.
InetUp *float64 `json:"inetUp,omitempty" tf:"inet_up,omitempty"`

// (Number) ID of the machine hosting this volume.
// ID of the machine hosting this volume.
MachineID *float64 `json:"machineId,omitempty" tf:"machine_id,omitempty"`

// (String) Optional name/label for the volume. Changes force replacement.
// Optional name/label for the volume. Changes force replacement.
Name *string `json:"name,omitempty" tf:"name,omitempty"`

// time attribute not returned by the API; preserved in state via UseStateForUnknown.
// ID of the volume offer to create from (from vastai_volume_offers data source). When cloning, this is the destination offer ID. Changes force replacement. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
OfferID *float64 `json:"offerId,omitempty" tf:"offer_id,omitempty"`

// (Number) Host reliability score (0.0 to 1.0).
// Host reliability score (0.0 to 1.0).
Reliability *float64 `json:"reliability,omitempty" tf:"reliability,omitempty"`

// time attribute not returned by the API; preserved in state via UseStateForUnknown.
// Volume size in GB. Changes force replacement. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

// (String) Current status of the volume (e.g., 'active', 'inactive').
// Current status of the volume (e.g., 'active', 'inactive').
Status *string `json:"status,omitempty" tf:"status,omitempty"`

// (String) Host verification status.
// Host verification status.
Verification *string `json:"verification,omitempty" tf:"verification,omitempty"`
}


type VolumeParameters struct {


// (Number) Source volume ID to clone from. When set, creates by cloning (POST /volumes/copy/) instead of creating from offer. Changes force replacement.
// Source volume ID to clone from. When set, creates by cloning (POST /volumes/copy/) instead of creating from offer. Changes force replacement.
// +kubebuilder:validation:Optional
CloneFromID *float64 `json:"cloneFromId,omitempty" tf:"clone_from_id,omitempty"`

// (Boolean) Disable compression during clone. Only used when clone_from_id is set. Changes force replacement.
// Disable compression during clone. Only used when clone_from_id is set. Changes force replacement.
// +kubebuilder:validation:Optional
DisableCompression *bool `json:"disableCompression,omitempty" tf:"disable_compression,omitempty"`

// (String) Optional name/label for the volume. Changes force replacement.
// Optional name/label for the volume. Changes force replacement.
// +kubebuilder:validation:Optional
Name *string `json:"name,omitempty" tf:"name,omitempty"`

// time attribute not returned by the API; preserved in state via UseStateForUnknown.
// ID of the volume offer to create from (from vastai_volume_offers data source). When cloning, this is the destination offer ID. Changes force replacement. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
// +kubebuilder:validation:Optional
OfferID *float64 `json:"offerId,omitempty" tf:"offer_id,omitempty"`

// time attribute not returned by the API; preserved in state via UseStateForUnknown.
// Volume size in GB. Changes force replacement. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
// +kubebuilder:validation:Optional
Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

// VolumeSpec defines the desired state of Volume
type VolumeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider       VolumeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider       VolumeInitParameters `json:"initProvider,omitempty"`
}

// VolumeStatus defines the observed state of Volume.
type VolumeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider          VolumeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion


// Volume is the Schema for the Volumes API. Manages a Vast.ai local volume.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vastai}
type Volume struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VolumeSpec   `json:"spec"`
	Status            VolumeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VolumeList contains a list of Volumes
type VolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Volume `json:"items"`
}

// Repository type metadata.
var (
	Volume_Kind             = "Volume"
	Volume_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Volume_Kind}.String()
	Volume_KindAPIVersion   = Volume_Kind + "." + CRDGroupVersion.String()
	Volume_GroupVersionKind = CRDGroupVersion.WithKind(Volume_Kind)
)

func init() {
	SchemeBuilder.Register(&Volume{}, &VolumeList{})
}
