// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InstanceTemplateInitParameters struct {

	// (String) Short description of the template.
	// Short description of the template.
	Desc *string `json:"desc,omitempty" tf:"desc,omitempty"`

	// (String, Sensitive) Private Docker registry URL for authenticated image pulls. This value is sensitive and will not be displayed in plan output.
	// Private Docker registry URL for authenticated image pulls. This value is sensitive and will not be displayed in plan output.
	DockerLoginRepoSecretRef *v1.LocalSecretKeySelector `json:"dockerLoginRepoSecretRef,omitempty" tf:"-"`

	// e KEY=VALUE -p 8080:8080'). Passed directly to the container runtime.
	// Environment variables and port mappings in Docker CLI format (e.g., '-e KEY=VALUE -p 8080:8080'). Passed directly to the container runtime.
	Env *string `json:"env,omitempty" tf:"env,omitempty"`

	// populated from Docker image metadata.
	// External URL associated with the template (e.g., documentation or project page). May be auto-populated from Docker image metadata.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// devel'). Must be a valid Docker image reference.
	// Docker image reference (e.g., 'pytorch/pytorch:latest', 'nvidia/cuda:12.0-devel'). Must be a valid Docker image reference.
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Boolean) Enable direct Jupyter access to instances created from this template.
	// Enable direct Jupyter access to instances created from this template.
	JupDirect *bool `json:"jupDirect,omitempty" tf:"jup_direct,omitempty"`

	// (String) Working directory for Jupyter when the instance starts.
	// Working directory for Jupyter when the instance starts.
	JupyterDir *string `json:"jupyterDir,omitempty" tf:"jupyter_dir,omitempty"`

	// (String) Template name. Must be between 1 and 200 characters.
	// Template name. Must be between 1 and 200 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Bash script to run when the instance starts. Executed after the container is initialized.
	// Bash script to run when the instance starts. Executed after the container is initialized.
	Onstart *string `json:"onstart,omitempty" tf:"onstart,omitempty"`

	// (Boolean) Whether this template is private (only visible to the owner). Default: false.
	// Whether this template is private (only visible to the owner). Default: false.
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String) Markdown readme content displayed on the template listing page.
	// Markdown readme content displayed on the template listing page.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (Boolean) Whether the readme is visible on the template listing.
	// Whether the readme is visible on the template listing.
	ReadmeVisible *bool `json:"readmeVisible,omitempty" tf:"readme_visible,omitempty"`

	// (String) Recommended disk space for instances using this template (e.g., '50GB').
	// Recommended disk space for instances using this template (e.g., '50GB').
	RecommendedDiskSpace *string `json:"recommendedDiskSpace,omitempty" tf:"recommended_disk_space,omitempty"`

	// populated from Docker image metadata.
	// Source code repository URL for the template. May be auto-populated from Docker image metadata.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`

	// (Boolean) Enable direct SSH access to instances created from this template.
	// Enable direct SSH access to instances created from this template.
	SSHDirect *bool `json:"sshDirect,omitempty" tf:"ssh_direct,omitempty"`

	// (String) Docker image tag. If not set, the API may assign a default based on the image reference.
	// Docker image tag. If not set, the API may assign a default based on the image reference.
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`

	// (Boolean) Use JupyterLab instead of classic Jupyter Notebook interface.
	// Use JupyterLab instead of classic Jupyter Notebook interface.
	UseJupyterLab *bool `json:"useJupyterLab,omitempty" tf:"use_jupyter_lab,omitempty"`

	// (Boolean) Enable SSH server in instances created from this template.
	// Enable SSH server in instances created from this template.
	UseSSH *bool `json:"useSsh,omitempty" tf:"use_ssh,omitempty"`
}

type InstanceTemplateObservation struct {

	// (String) Timestamp when the template was created (set by the API).
	// Timestamp when the template was created (set by the API).
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Short description of the template.
	// Short description of the template.
	Desc *string `json:"desc,omitempty" tf:"desc,omitempty"`

	// e KEY=VALUE -p 8080:8080'). Passed directly to the container runtime.
	// Environment variables and port mappings in Docker CLI format (e.g., '-e KEY=VALUE -p 8080:8080'). Passed directly to the container runtime.
	Env *string `json:"env,omitempty" tf:"env,omitempty"`

	// addressed template hash ID. Changes when template content is updated.
	// Content-addressed template hash ID. Changes when template content is updated.
	HashID *string `json:"hashId,omitempty" tf:"hash_id,omitempty"`

	// populated from Docker image metadata.
	// External URL associated with the template (e.g., documentation or project page). May be auto-populated from Docker image metadata.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// (String) Numeric template ID (stable across updates).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// devel'). Must be a valid Docker image reference.
	// Docker image reference (e.g., 'pytorch/pytorch:latest', 'nvidia/cuda:12.0-devel'). Must be a valid Docker image reference.
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Boolean) Enable direct Jupyter access to instances created from this template.
	// Enable direct Jupyter access to instances created from this template.
	JupDirect *bool `json:"jupDirect,omitempty" tf:"jup_direct,omitempty"`

	// (String) Working directory for Jupyter when the instance starts.
	// Working directory for Jupyter when the instance starts.
	JupyterDir *string `json:"jupyterDir,omitempty" tf:"jupyter_dir,omitempty"`

	// (String) Template name. Must be between 1 and 200 characters.
	// Template name. Must be between 1 and 200 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Numeric template ID assigned by the Vast.ai API (same as id, typed as integer).
	// Numeric template ID assigned by the Vast.ai API (same as id, typed as integer).
	NumericID *float64 `json:"numericId,omitempty" tf:"numeric_id,omitempty"`

	// (String) Bash script to run when the instance starts. Executed after the container is initialized.
	// Bash script to run when the instance starts. Executed after the container is initialized.
	Onstart *string `json:"onstart,omitempty" tf:"onstart,omitempty"`

	// (Boolean) Whether this template is private (only visible to the owner). Default: false.
	// Whether this template is private (only visible to the owner). Default: false.
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String) Markdown readme content displayed on the template listing page.
	// Markdown readme content displayed on the template listing page.
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (Boolean) Whether the readme is visible on the template listing.
	// Whether the readme is visible on the template listing.
	ReadmeVisible *bool `json:"readmeVisible,omitempty" tf:"readme_visible,omitempty"`

	// (String) Recommended disk space for instances using this template (e.g., '50GB').
	// Recommended disk space for instances using this template (e.g., '50GB').
	RecommendedDiskSpace *string `json:"recommendedDiskSpace,omitempty" tf:"recommended_disk_space,omitempty"`

	// populated from Docker image metadata.
	// Source code repository URL for the template. May be auto-populated from Docker image metadata.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`

	// (Boolean) Enable direct SSH access to instances created from this template.
	// Enable direct SSH access to instances created from this template.
	SSHDirect *bool `json:"sshDirect,omitempty" tf:"ssh_direct,omitempty"`

	// (String) Docker image tag. If not set, the API may assign a default based on the image reference.
	// Docker image tag. If not set, the API may assign a default based on the image reference.
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`

	// (Boolean) Use JupyterLab instead of classic Jupyter Notebook interface.
	// Use JupyterLab instead of classic Jupyter Notebook interface.
	UseJupyterLab *bool `json:"useJupyterLab,omitempty" tf:"use_jupyter_lab,omitempty"`

	// (Boolean) Enable SSH server in instances created from this template.
	// Enable SSH server in instances created from this template.
	UseSSH *bool `json:"useSsh,omitempty" tf:"use_ssh,omitempty"`
}

type InstanceTemplateParameters struct {

	// (String) Short description of the template.
	// Short description of the template.
	// +kubebuilder:validation:Optional
	Desc *string `json:"desc,omitempty" tf:"desc,omitempty"`

	// (String, Sensitive) Private Docker registry URL for authenticated image pulls. This value is sensitive and will not be displayed in plan output.
	// Private Docker registry URL for authenticated image pulls. This value is sensitive and will not be displayed in plan output.
	// +kubebuilder:validation:Optional
	DockerLoginRepoSecretRef *v1.LocalSecretKeySelector `json:"dockerLoginRepoSecretRef,omitempty" tf:"-"`

	// e KEY=VALUE -p 8080:8080'). Passed directly to the container runtime.
	// Environment variables and port mappings in Docker CLI format (e.g., '-e KEY=VALUE -p 8080:8080'). Passed directly to the container runtime.
	// +kubebuilder:validation:Optional
	Env *string `json:"env,omitempty" tf:"env,omitempty"`

	// populated from Docker image metadata.
	// External URL associated with the template (e.g., documentation or project page). May be auto-populated from Docker image metadata.
	// +kubebuilder:validation:Optional
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// devel'). Must be a valid Docker image reference.
	// Docker image reference (e.g., 'pytorch/pytorch:latest', 'nvidia/cuda:12.0-devel'). Must be a valid Docker image reference.
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Boolean) Enable direct Jupyter access to instances created from this template.
	// Enable direct Jupyter access to instances created from this template.
	// +kubebuilder:validation:Optional
	JupDirect *bool `json:"jupDirect,omitempty" tf:"jup_direct,omitempty"`

	// (String) Working directory for Jupyter when the instance starts.
	// Working directory for Jupyter when the instance starts.
	// +kubebuilder:validation:Optional
	JupyterDir *string `json:"jupyterDir,omitempty" tf:"jupyter_dir,omitempty"`

	// (String) Template name. Must be between 1 and 200 characters.
	// Template name. Must be between 1 and 200 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Bash script to run when the instance starts. Executed after the container is initialized.
	// Bash script to run when the instance starts. Executed after the container is initialized.
	// +kubebuilder:validation:Optional
	Onstart *string `json:"onstart,omitempty" tf:"onstart,omitempty"`

	// (Boolean) Whether this template is private (only visible to the owner). Default: false.
	// Whether this template is private (only visible to the owner). Default: false.
	// +kubebuilder:validation:Optional
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String) Markdown readme content displayed on the template listing page.
	// Markdown readme content displayed on the template listing page.
	// +kubebuilder:validation:Optional
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (Boolean) Whether the readme is visible on the template listing.
	// Whether the readme is visible on the template listing.
	// +kubebuilder:validation:Optional
	ReadmeVisible *bool `json:"readmeVisible,omitempty" tf:"readme_visible,omitempty"`

	// (String) Recommended disk space for instances using this template (e.g., '50GB').
	// Recommended disk space for instances using this template (e.g., '50GB').
	// +kubebuilder:validation:Optional
	RecommendedDiskSpace *string `json:"recommendedDiskSpace,omitempty" tf:"recommended_disk_space,omitempty"`

	// populated from Docker image metadata.
	// Source code repository URL for the template. May be auto-populated from Docker image metadata.
	// +kubebuilder:validation:Optional
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`

	// (Boolean) Enable direct SSH access to instances created from this template.
	// Enable direct SSH access to instances created from this template.
	// +kubebuilder:validation:Optional
	SSHDirect *bool `json:"sshDirect,omitempty" tf:"ssh_direct,omitempty"`

	// (String) Docker image tag. If not set, the API may assign a default based on the image reference.
	// Docker image tag. If not set, the API may assign a default based on the image reference.
	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`

	// (Boolean) Use JupyterLab instead of classic Jupyter Notebook interface.
	// Use JupyterLab instead of classic Jupyter Notebook interface.
	// +kubebuilder:validation:Optional
	UseJupyterLab *bool `json:"useJupyterLab,omitempty" tf:"use_jupyter_lab,omitempty"`

	// (Boolean) Enable SSH server in instances created from this template.
	// Enable SSH server in instances created from this template.
	// +kubebuilder:validation:Optional
	UseSSH *bool `json:"useSsh,omitempty" tf:"use_ssh,omitempty"`
}

// InstanceTemplateSpec defines the desired state of InstanceTemplate
type InstanceTemplateSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InstanceTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceTemplateInitParameters `json:"initProvider,omitempty"`
}

// InstanceTemplateStatus defines the observed state of InstanceTemplate.
type InstanceTemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InstanceTemplate is the Schema for the InstanceTemplates API. Manages a Vast.ai template.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vastai}
type InstanceTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.image) || (has(self.initProvider) && has(self.initProvider.image))",message="spec.forProvider.image is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   InstanceTemplateSpec   `json:"spec"`
	Status InstanceTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceTemplateList contains a list of InstanceTemplates
type InstanceTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstanceTemplate `json:"items"`
}

// Repository type metadata.
var (
	InstanceTemplate_Kind             = "InstanceTemplate"
	InstanceTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InstanceTemplate_Kind}.String()
	InstanceTemplate_KindAPIVersion   = InstanceTemplate_Kind + "." + CRDGroupVersion.String()
	InstanceTemplate_GroupVersionKind = CRDGroupVersion.WithKind(InstanceTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&InstanceTemplate{}, &InstanceTemplateList{})
}
