// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TeamMemberInitParameters struct {

	// inviting the member.
	// Email address to invite. Changing this requires removing and re-inviting the member.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// inviting the member.
	// Role name to assign to the member. Must match an existing team role. Changing the role requires removing and re-inviting the member.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type TeamMemberObservation struct {

	// inviting the member.
	// Email address to invite. Changing this requires removing and re-inviting the member.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) Member ID assigned by Vast.ai.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// inviting the member.
	// Role name to assign to the member. Must match an existing team role. Changing the role requires removing and re-inviting the member.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type TeamMemberParameters struct {

	// inviting the member.
	// Email address to invite. Changing this requires removing and re-inviting the member.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// inviting the member.
	// Role name to assign to the member. Must match an existing team role. Changing the role requires removing and re-inviting the member.
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

// TeamMemberSpec defines the desired state of TeamMember
type TeamMemberSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TeamMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamMemberInitParameters `json:"initProvider,omitempty"`
}

// TeamMemberStatus defines the observed state of TeamMember.
type TeamMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TeamMember is the Schema for the TeamMembers API. Manages a Vast.ai team member.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vastai}
type TeamMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	Spec   TeamMemberSpec   `json:"spec"`
	Status TeamMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamMemberList contains a list of TeamMembers
type TeamMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TeamMember `json:"items"`
}

// Repository type metadata.
var (
	TeamMember_Kind             = "TeamMember"
	TeamMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TeamMember_Kind}.String()
	TeamMember_KindAPIVersion   = TeamMember_Kind + "." + CRDGroupVersion.String()
	TeamMember_GroupVersionKind = CRDGroupVersion.WithKind(TeamMember_Kind)
)

func init() {
	SchemeBuilder.Register(&TeamMember{}, &TeamMemberList{})
}
