// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TeamRoleInitParameters struct {

	// (String) Role name (used for read/delete operations).
	// Role name (used for read/delete operations).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) JSON string of permission configuration. The API uses nested JSON objects (e.g., {"api":{"instance_read":{...}}}), not a flat string set.
	// JSON string of permission configuration. The API uses nested JSON objects (e.g., {"api":{"instance_read":{...}}}), not a flat string set.
	Permissions *string `json:"permissions,omitempty" tf:"permissions,omitempty"`
}

type TeamRoleObservation struct {

	// (String) Numeric ID of the role (used for updates).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Role name (used for read/delete operations).
	// Role name (used for read/delete operations).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) JSON string of permission configuration. The API uses nested JSON objects (e.g., {"api":{"instance_read":{...}}}), not a flat string set.
	// JSON string of permission configuration. The API uses nested JSON objects (e.g., {"api":{"instance_read":{...}}}), not a flat string set.
	Permissions *string `json:"permissions,omitempty" tf:"permissions,omitempty"`
}

type TeamRoleParameters struct {

	// (String) Role name (used for read/delete operations).
	// Role name (used for read/delete operations).
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) JSON string of permission configuration. The API uses nested JSON objects (e.g., {"api":{"instance_read":{...}}}), not a flat string set.
	// JSON string of permission configuration. The API uses nested JSON objects (e.g., {"api":{"instance_read":{...}}}), not a flat string set.
	// +kubebuilder:validation:Optional
	Permissions *string `json:"permissions,omitempty" tf:"permissions,omitempty"`
}

// TeamRoleSpec defines the desired state of TeamRole
type TeamRoleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TeamRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamRoleInitParameters `json:"initProvider,omitempty"`
}

// TeamRoleStatus defines the observed state of TeamRole.
type TeamRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TeamRole is the Schema for the TeamRoles API. Manages a Vast.ai team role.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vastai}
type TeamRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissions) || (has(self.initProvider) && has(self.initProvider.permissions))",message="spec.forProvider.permissions is a required parameter"
	Spec   TeamRoleSpec   `json:"spec"`
	Status TeamRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamRoleList contains a list of TeamRoles
type TeamRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TeamRole `json:"items"`
}

// Repository type metadata.
var (
	TeamRole_Kind             = "TeamRole"
	TeamRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TeamRole_Kind}.String()
	TeamRole_KindAPIVersion   = TeamRole_Kind + "." + CRDGroupVersion.String()
	TeamRole_GroupVersionKind = CRDGroupVersion.WithKind(TeamRole_Kind)
)

func init() {
	SchemeBuilder.Register(&TeamRole{}, &TeamRoleList{})
}
