// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ClusterMemberInitParameters struct {

	// (String) ID of the cluster to join.
	// ID of the cluster to join.
	// +crossplane:generate:reference:type=github.com/Lazlovalentin/crossplane-provider-vast.ai/apis/namespaced/compute/v1alpha1.Cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) ID of the machine to add to the cluster.
	// ID of the machine to add to the cluster.
	MachineID *string `json:"machineId,omitempty" tf:"machine_id,omitempty"`

	// (String) If removing the cluster manager, specify the new manager machine ID. Only used during destroy.
	// If removing the cluster manager, specify the new manager machine ID. Only used during destroy.
	NewManagerID *string `json:"newManagerId,omitempty" tf:"new_manager_id,omitempty"`
}

type ClusterMemberObservation struct {

	// (String) ID of the cluster to join.
	// ID of the cluster to join.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Composite ID: cluster_id/machine_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Whether this machine is the cluster manager.
	// Whether this machine is the cluster manager.
	IsClusterManager *bool `json:"isClusterManager,omitempty" tf:"is_cluster_manager,omitempty"`

	// (String) Local IP address of the machine within the cluster network.
	// Local IP address of the machine within the cluster network.
	LocalIP *string `json:"localIp,omitempty" tf:"local_ip,omitempty"`

	// (String) ID of the machine to add to the cluster.
	// ID of the machine to add to the cluster.
	MachineID *string `json:"machineId,omitempty" tf:"machine_id,omitempty"`

	// (String) If removing the cluster manager, specify the new manager machine ID. Only used during destroy.
	// If removing the cluster manager, specify the new manager machine ID. Only used during destroy.
	NewManagerID *string `json:"newManagerId,omitempty" tf:"new_manager_id,omitempty"`
}

type ClusterMemberParameters struct {

	// (String) ID of the cluster to join.
	// ID of the cluster to join.
	// +crossplane:generate:reference:type=github.com/Lazlovalentin/crossplane-provider-vast.ai/apis/namespaced/compute/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) ID of the machine to add to the cluster.
	// ID of the machine to add to the cluster.
	// +kubebuilder:validation:Optional
	MachineID *string `json:"machineId,omitempty" tf:"machine_id,omitempty"`

	// (String) If removing the cluster manager, specify the new manager machine ID. Only used during destroy.
	// If removing the cluster manager, specify the new manager machine ID. Only used during destroy.
	// +kubebuilder:validation:Optional
	NewManagerID *string `json:"newManagerId,omitempty" tf:"new_manager_id,omitempty"`
}

// ClusterMemberSpec defines the desired state of ClusterMember
type ClusterMemberSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ClusterMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterMemberInitParameters `json:"initProvider,omitempty"`
}

// ClusterMemberStatus defines the observed state of ClusterMember.
type ClusterMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterMember is the Schema for the ClusterMembers API. Manages membership of a machine in a Vast.ai cluster.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vastai}
type ClusterMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.machineId) || (has(self.initProvider) && has(self.initProvider.machineId))",message="spec.forProvider.machineId is a required parameter"
	Spec   ClusterMemberSpec   `json:"spec"`
	Status ClusterMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterMemberList contains a list of ClusterMembers
type ClusterMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterMember `json:"items"`
}

// Repository type metadata.
var (
	ClusterMember_Kind             = "ClusterMember"
	ClusterMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterMember_Kind}.String()
	ClusterMember_KindAPIVersion   = ClusterMember_Kind + "." + CRDGroupVersion.String()
	ClusterMember_GroupVersionKind = CRDGroupVersion.WithKind(ClusterMember_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterMember{}, &ClusterMemberList{})
}
