// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InstanceInitParameters struct {

	// demand pricing. The bid amount can be updated in-place, but removing bid pricing entirely (switching from spot to on-demand) requires instance replacement.
	// Bid price per GPU per hour in USD. Set to create an interruptible (spot) instance. Omit for on-demand pricing. The bid amount can be updated in-place, but removing bid pricing entirely (switching from spot to on-demand) requires instance replacement.
	BidPrice *float64 `json:"bidPrice,omitempty" tf:"bid_price,omitempty"`

	// time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// Cancel instance creation if the selected offer becomes unavailable. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	CancelUnavail *bool `json:"cancelUnavail,omitempty" tf:"cancel_unavail,omitempty"`

	// time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// Local disk partition size in GB. Cannot be changed after creation. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	DiskGb *float64 `json:"diskGb,omitempty" tf:"disk_gb,omitempty"`

	// value pairs passed to the instance container. Can be updated via template update. Not returned by the API; preserved in state via UseStateForUnknown.
	// Environment variables as key-value pairs passed to the instance container. Can be updated via template update. Not returned by the API; preserved in state via UseStateForUnknown.
	// +mapType=granular
	Env map[string]*string `json:"env,omitempty" tf:"env,omitempty"`

	// (String) Docker image to launch (e.g., 'pytorch/pytorch:latest'). Can be set via template. If not specified, the template's image is used. Note: the API may return an image UUID instead of the original docker reference; the state value is preserved from config when possible.
	// Docker image to launch (e.g., 'pytorch/pytorch:latest'). Can be set via template. If not specified, the template's image is used. Note: the API may return an image UUID instead of the original docker reference; the state value is preserved from config when possible.
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// u user -p pass registry'). This value is sensitive and will not be displayed in plan output. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// Docker registry credentials for private image pulls (format: '-u user -p pass registry'). This value is sensitive and will not be displayed in plan output. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	ImageLoginSecretRef *v1.LocalSecretKeySelector `json:"imageLoginSecretRef,omitempty" tf:"-"`

	// readable label for the instance. Can be updated in-place.
	// Human-readable label for the instance. Can be updated in-place.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// ID of the GPU offer to create this instance from. Obtain from the vastai_gpu_offers data source. Changing this forces a new resource. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	OfferID *float64 `json:"offerId,omitempty" tf:"offer_id,omitempty"`

	// (String) Startup script executed when the instance boots. Can be updated via template update.
	// Startup script executed when the instance boots. Can be updated via template update.
	Onstart *string `json:"onstart,omitempty" tf:"onstart,omitempty"`

	// (Set of String) Set of SSH key IDs to attach to this instance. Keys are attached/detached incrementally when the set changes. Use IDs from vastai_ssh_key resources. Not returned by the API; preserved in state via UseStateForUnknown.
	// Set of SSH key IDs to attach to this instance. Keys are attached/detached incrementally when the set changes. Use IDs from vastai_ssh_key resources. Not returned by the API; preserved in state via UseStateForUnknown.
	// +listType=set
	SSHKeyIds []*string `json:"sshKeyIds,omitempty" tf:"ssh_key_ids,omitempty"`

	// (String) Desired instance state. Set to 'running' or 'stopped' to start/stop the instance without destroying and recreating it. Defaults to 'running' on creation.
	// Desired instance state. Set to 'running' or 'stopped' to start/stop the instance without destroying and recreating it. Defaults to 'running' on creation.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// place.
	// Hash ID of a Vast.ai template to apply to this instance. Can be updated in-place.
	TemplateHashID *string `json:"templateHashId,omitempty" tf:"template_hash_id,omitempty"`

	// time attribute not returned by the API.
	// Enable JupyterLab access to this instance. Defaults to the template setting if not specified. This is a creation-time attribute not returned by the API.
	UseJupyterLab *bool `json:"useJupyterLab,omitempty" tf:"use_jupyter_lab,omitempty"`

	// time attribute not returned by the API.
	// Enable SSH access to this instance. Defaults to the template setting if not specified. This is a creation-time attribute not returned by the API.
	UseSSH *bool `json:"useSsh,omitempty" tf:"use_ssh,omitempty"`
}

type InstanceObservation struct {

	// (String) Current actual status of the instance as reported by the API (e.g., 'running', 'loading', 'exited').
	// Current actual status of the instance as reported by the API (e.g., 'running', 'loading', 'exited').
	ActualStatus *string `json:"actualStatus,omitempty" tf:"actual_status,omitempty"`

	// demand pricing. The bid amount can be updated in-place, but removing bid pricing entirely (switching from spot to on-demand) requires instance replacement.
	// Bid price per GPU per hour in USD. Set to create an interruptible (spot) instance. Omit for on-demand pricing. The bid amount can be updated in-place, but removing bid pricing entirely (switching from spot to on-demand) requires instance replacement.
	BidPrice *float64 `json:"bidPrice,omitempty" tf:"bid_price,omitempty"`

	// (Number) Number of effective CPU cores allocated to this instance.
	// Number of effective CPU cores allocated to this instance.
	CPUCores *float64 `json:"cpuCores,omitempty" tf:"cpu_cores,omitempty"`

	// (Number) Total CPU RAM in GB.
	// Total CPU RAM in GB.
	CPURAMGb *float64 `json:"cpuRamGb,omitempty" tf:"cpu_ram_gb,omitempty"`

	// time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// Cancel instance creation if the selected offer becomes unavailable. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	CancelUnavail *bool `json:"cancelUnavail,omitempty" tf:"cancel_unavail,omitempty"`

	// (Number) Current cost per hour in USD for this instance.
	// Current cost per hour in USD for this instance.
	CostPerHour *float64 `json:"costPerHour,omitempty" tf:"cost_per_hour,omitempty"`

	// (String) Timestamp when the instance was created.
	// Timestamp when the instance was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// Local disk partition size in GB. Cannot be changed after creation. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	DiskGb *float64 `json:"diskGb,omitempty" tf:"disk_gb,omitempty"`

	// value pairs passed to the instance container. Can be updated via template update. Not returned by the API; preserved in state via UseStateForUnknown.
	// Environment variables as key-value pairs passed to the instance container. Can be updated via template update. Not returned by the API; preserved in state via UseStateForUnknown.
	// +mapType=granular
	Env map[string]*string `json:"env,omitempty" tf:"env,omitempty"`

	// (String) Geographic location of the host machine.
	// Geographic location of the host machine.
	Geolocation *string `json:"geolocation,omitempty" tf:"geolocation,omitempty"`

	// (String) GPU model name (e.g., 'RTX 4090', 'A100 SXM4').
	// GPU model name (e.g., 'RTX 4090', 'A100 SXM4').
	GpuName *string `json:"gpuName,omitempty" tf:"gpu_name,omitempty"`

	// (Number) Total GPU VRAM in GB.
	// Total GPU VRAM in GB.
	GpuRAMGb *float64 `json:"gpuRamGb,omitempty" tf:"gpu_ram_gb,omitempty"`

	// (String) Unique contract ID of the instance. Used as the primary identifier for all operations.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Docker image to launch (e.g., 'pytorch/pytorch:latest'). Can be set via template. If not specified, the template's image is used. Note: the API may return an image UUID instead of the original docker reference; the state value is preserved from config when possible.
	// Docker image to launch (e.g., 'pytorch/pytorch:latest'). Can be set via template. If not specified, the template's image is used. Note: the API may return an image UUID instead of the original docker reference; the state value is preserved from config when possible.
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// (Number) Internet download speed in Mbps.
	// Internet download speed in Mbps.
	InetDownMbps *float64 `json:"inetDownMbps,omitempty" tf:"inet_down_mbps,omitempty"`

	// (Number) Internet upload speed in Mbps.
	// Internet upload speed in Mbps.
	InetUpMbps *float64 `json:"inetUpMbps,omitempty" tf:"inet_up_mbps,omitempty"`

	// (Boolean) Whether this instance uses bid (spot/interruptible) pricing.
	// Whether this instance uses bid (spot/interruptible) pricing.
	IsBid *bool `json:"isBid,omitempty" tf:"is_bid,omitempty"`

	// readable label for the instance. Can be updated in-place.
	// Human-readable label for the instance. Can be updated in-place.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (Number) Physical machine ID hosting this instance.
	// Physical machine ID hosting this instance.
	MachineID *float64 `json:"machineId,omitempty" tf:"machine_id,omitempty"`

	// (Number) Number of GPUs allocated to this instance.
	// Number of GPUs allocated to this instance.
	NumGpus *float64 `json:"numGpus,omitempty" tf:"num_gpus,omitempty"`

	// time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// ID of the GPU offer to create this instance from. Obtain from the vastai_gpu_offers data source. Changing this forces a new resource. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	OfferID *float64 `json:"offerId,omitempty" tf:"offer_id,omitempty"`

	// (String) Startup script executed when the instance boots. Can be updated via template update.
	// Startup script executed when the instance boots. Can be updated via template update.
	Onstart *string `json:"onstart,omitempty" tf:"onstart,omitempty"`

	// (Number) Host machine reliability score (0.0 to 1.0).
	// Host machine reliability score (0.0 to 1.0).
	Reliability *float64 `json:"reliability,omitempty" tf:"reliability,omitempty"`

	// (String) SSH connection hostname for this instance.
	// SSH connection hostname for this instance.
	SSHHost *string `json:"sshHost,omitempty" tf:"ssh_host,omitempty"`

	// (Set of String) Set of SSH key IDs to attach to this instance. Keys are attached/detached incrementally when the set changes. Use IDs from vastai_ssh_key resources. Not returned by the API; preserved in state via UseStateForUnknown.
	// Set of SSH key IDs to attach to this instance. Keys are attached/detached incrementally when the set changes. Use IDs from vastai_ssh_key resources. Not returned by the API; preserved in state via UseStateForUnknown.
	// +listType=set
	SSHKeyIds []*string `json:"sshKeyIds,omitempty" tf:"ssh_key_ids,omitempty"`

	// (Number) SSH connection port for this instance.
	// SSH connection port for this instance.
	SSHPort *float64 `json:"sshPort,omitempty" tf:"ssh_port,omitempty"`

	// (String) Desired instance state. Set to 'running' or 'stopped' to start/stop the instance without destroying and recreating it. Defaults to 'running' on creation.
	// Desired instance state. Set to 'running' or 'stopped' to start/stop the instance without destroying and recreating it. Defaults to 'running' on creation.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Current status message from the instance (e.g., progress information during loading).
	// Current status message from the instance (e.g., progress information during loading).
	StatusMsg *string `json:"statusMsg,omitempty" tf:"status_msg,omitempty"`

	// place.
	// Hash ID of a Vast.ai template to apply to this instance. Can be updated in-place.
	TemplateHashID *string `json:"templateHashId,omitempty" tf:"template_hash_id,omitempty"`

	// time attribute not returned by the API.
	// Enable JupyterLab access to this instance. Defaults to the template setting if not specified. This is a creation-time attribute not returned by the API.
	UseJupyterLab *bool `json:"useJupyterLab,omitempty" tf:"use_jupyter_lab,omitempty"`

	// time attribute not returned by the API.
	// Enable SSH access to this instance. Defaults to the template setting if not specified. This is a creation-time attribute not returned by the API.
	UseSSH *bool `json:"useSsh,omitempty" tf:"use_ssh,omitempty"`
}

type InstanceParameters struct {

	// demand pricing. The bid amount can be updated in-place, but removing bid pricing entirely (switching from spot to on-demand) requires instance replacement.
	// Bid price per GPU per hour in USD. Set to create an interruptible (spot) instance. Omit for on-demand pricing. The bid amount can be updated in-place, but removing bid pricing entirely (switching from spot to on-demand) requires instance replacement.
	// +kubebuilder:validation:Optional
	BidPrice *float64 `json:"bidPrice,omitempty" tf:"bid_price,omitempty"`

	// time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// Cancel instance creation if the selected offer becomes unavailable. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// +kubebuilder:validation:Optional
	CancelUnavail *bool `json:"cancelUnavail,omitempty" tf:"cancel_unavail,omitempty"`

	// time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// Local disk partition size in GB. Cannot be changed after creation. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// +kubebuilder:validation:Optional
	DiskGb *float64 `json:"diskGb,omitempty" tf:"disk_gb,omitempty"`

	// value pairs passed to the instance container. Can be updated via template update. Not returned by the API; preserved in state via UseStateForUnknown.
	// Environment variables as key-value pairs passed to the instance container. Can be updated via template update. Not returned by the API; preserved in state via UseStateForUnknown.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Env map[string]*string `json:"env,omitempty" tf:"env,omitempty"`

	// (String) Docker image to launch (e.g., 'pytorch/pytorch:latest'). Can be set via template. If not specified, the template's image is used. Note: the API may return an image UUID instead of the original docker reference; the state value is preserved from config when possible.
	// Docker image to launch (e.g., 'pytorch/pytorch:latest'). Can be set via template. If not specified, the template's image is used. Note: the API may return an image UUID instead of the original docker reference; the state value is preserved from config when possible.
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// u user -p pass registry'). This value is sensitive and will not be displayed in plan output. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// Docker registry credentials for private image pulls (format: '-u user -p pass registry'). This value is sensitive and will not be displayed in plan output. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// +kubebuilder:validation:Optional
	ImageLoginSecretRef *v1.LocalSecretKeySelector `json:"imageLoginSecretRef,omitempty" tf:"-"`

	// readable label for the instance. Can be updated in-place.
	// Human-readable label for the instance. Can be updated in-place.
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// ID of the GPU offer to create this instance from. Obtain from the vastai_gpu_offers data source. Changing this forces a new resource. This is a creation-time attribute not returned by the API; preserved in state via UseStateForUnknown.
	// +kubebuilder:validation:Optional
	OfferID *float64 `json:"offerId,omitempty" tf:"offer_id,omitempty"`

	// (String) Startup script executed when the instance boots. Can be updated via template update.
	// Startup script executed when the instance boots. Can be updated via template update.
	// +kubebuilder:validation:Optional
	Onstart *string `json:"onstart,omitempty" tf:"onstart,omitempty"`

	// (Set of String) Set of SSH key IDs to attach to this instance. Keys are attached/detached incrementally when the set changes. Use IDs from vastai_ssh_key resources. Not returned by the API; preserved in state via UseStateForUnknown.
	// Set of SSH key IDs to attach to this instance. Keys are attached/detached incrementally when the set changes. Use IDs from vastai_ssh_key resources. Not returned by the API; preserved in state via UseStateForUnknown.
	// +kubebuilder:validation:Optional
	// +listType=set
	SSHKeyIds []*string `json:"sshKeyIds,omitempty" tf:"ssh_key_ids,omitempty"`

	// (String) Desired instance state. Set to 'running' or 'stopped' to start/stop the instance without destroying and recreating it. Defaults to 'running' on creation.
	// Desired instance state. Set to 'running' or 'stopped' to start/stop the instance without destroying and recreating it. Defaults to 'running' on creation.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// place.
	// Hash ID of a Vast.ai template to apply to this instance. Can be updated in-place.
	// +kubebuilder:validation:Optional
	TemplateHashID *string `json:"templateHashId,omitempty" tf:"template_hash_id,omitempty"`

	// time attribute not returned by the API.
	// Enable JupyterLab access to this instance. Defaults to the template setting if not specified. This is a creation-time attribute not returned by the API.
	// +kubebuilder:validation:Optional
	UseJupyterLab *bool `json:"useJupyterLab,omitempty" tf:"use_jupyter_lab,omitempty"`

	// time attribute not returned by the API.
	// Enable SSH access to this instance. Defaults to the template setting if not specified. This is a creation-time attribute not returned by the API.
	// +kubebuilder:validation:Optional
	UseSSH *bool `json:"useSsh,omitempty" tf:"use_ssh,omitempty"`
}

// InstanceSpec defines the desired state of Instance
type InstanceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceInitParameters `json:"initProvider,omitempty"`
}

// InstanceStatus defines the observed state of Instance.
type InstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Instance is the Schema for the Instances API. Manages a Vast.ai GPU instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vastai}
type Instance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              InstanceSpec   `json:"spec"`
	Status            InstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceList contains a list of Instances
type InstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Instance `json:"items"`
}

// Repository type metadata.
var (
	Instance_Kind             = "Instance"
	Instance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Instance_Kind}.String()
	Instance_KindAPIVersion   = Instance_Kind + "." + CRDGroupVersion.String()
	Instance_GroupVersionKind = CRDGroupVersion.WithKind(Instance_Kind)
)

func init() {
	SchemeBuilder.Register(&Instance{}, &InstanceList{})
}
