apiVersion: storage.vastai.crossplane.io/v1alpha1
kind: NetworkVolume
metadata:
  name: shared-checkpoints
spec:
  forProvider:
    offerId: 77001
    size: 1000
    name: shared-checkpoints
  providerConfigRef:
    name: default
