// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type OverlayInitParameters struct {

	// (String) ID of the cluster this overlay belongs to.
	// ID of the cluster this overlay belongs to.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Name of the overlay network.
	// Name of the overlay network.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OverlayObservation struct {

	// (String) ID of the cluster this overlay belongs to.
	// ID of the cluster this overlay belongs to.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Unique numeric identifier of the overlay.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Subnet assigned to the overlay.
	// Subnet assigned to the overlay.
	InternalSubnet *string `json:"internalSubnet,omitempty" tf:"internal_subnet,omitempty"`

	// (String) Name of the overlay network.
	// Name of the overlay network.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OverlayParameters struct {

	// (String) ID of the cluster this overlay belongs to.
	// ID of the cluster this overlay belongs to.
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Name of the overlay network.
	// Name of the overlay network.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// OverlaySpec defines the desired state of Overlay
type OverlaySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OverlayParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OverlayInitParameters `json:"initProvider,omitempty"`
}

// OverlayStatus defines the observed state of Overlay.
type OverlayStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OverlayObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Overlay is the Schema for the Overlays API. Manages a Vast.ai overlay network.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vastai}
type Overlay struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OverlaySpec   `json:"spec"`
	Status OverlayStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OverlayList contains a list of Overlays
type OverlayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Overlay `json:"items"`
}

// Repository type metadata.
var (
	Overlay_Kind             = "Overlay"
	Overlay_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Overlay_Kind}.String()
	Overlay_KindAPIVersion   = Overlay_Kind + "." + CRDGroupVersion.String()
	Overlay_GroupVersionKind = CRDGroupVersion.WithKind(Overlay_Kind)
)

func init() {
	SchemeBuilder.Register(&Overlay{}, &OverlayList{})
}
