// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0


// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"

)




type EnvironmentVariableInitParameters struct {


// (String) Environment variable name. Changing this forces a new resource.
// Environment variable name. Changing this forces a new resource.
Key *string `json:"key,omitempty" tf:"key,omitempty"`

// (String, Sensitive) Environment variable value.
// Environment variable value.
ValueSecretRef v1.SecretKeySelector `json:"valueSecretRef" tf:"-"`
}


type EnvironmentVariableObservation struct {


// (String) The environment variable name (same as key). Used as the unique identifier.
ID *string `json:"id,omitempty" tf:"id,omitempty"`

// (String) Environment variable name. Changing this forces a new resource.
// Environment variable name. Changing this forces a new resource.
Key *string `json:"key,omitempty" tf:"key,omitempty"`
}


type EnvironmentVariableParameters struct {


// (String) Environment variable name. Changing this forces a new resource.
// Environment variable name. Changing this forces a new resource.
// +kubebuilder:validation:Optional
Key *string `json:"key,omitempty" tf:"key,omitempty"`

// (String, Sensitive) Environment variable value.
// Environment variable value.
// +kubebuilder:validation:Optional
ValueSecretRef v1.SecretKeySelector `json:"valueSecretRef" tf:"-"`
}

// EnvironmentVariableSpec defines the desired state of EnvironmentVariable
type EnvironmentVariableSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider       EnvironmentVariableParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider       EnvironmentVariableInitParameters `json:"initProvider,omitempty"`
}

// EnvironmentVariableStatus defines the observed state of EnvironmentVariable.
type EnvironmentVariableStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider          EnvironmentVariableObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion


// EnvironmentVariable is the Schema for the EnvironmentVariables API. Manages a Vast.ai environment variable.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vastai}
type EnvironmentVariable struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.valueSecretRef)",message="spec.forProvider.valueSecretRef is a required parameter"
	Spec              EnvironmentVariableSpec   `json:"spec"`
	Status            EnvironmentVariableStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EnvironmentVariableList contains a list of EnvironmentVariables
type EnvironmentVariableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EnvironmentVariable `json:"items"`
}

// Repository type metadata.
var (
	EnvironmentVariable_Kind             = "EnvironmentVariable"
	EnvironmentVariable_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EnvironmentVariable_Kind}.String()
	EnvironmentVariable_KindAPIVersion   = EnvironmentVariable_Kind + "." + CRDGroupVersion.String()
	EnvironmentVariable_GroupVersionKind = CRDGroupVersion.WithKind(EnvironmentVariable_Kind)
)

func init() {
	SchemeBuilder.Register(&EnvironmentVariable{}, &EnvironmentVariableList{})
}
