// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0


// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"

)




type SubaccountInitParameters struct {


// (String) Email address for the subaccount. Changing this forces a new resource.
// Email address for the subaccount. Changing this forces a new resource.
Email *string `json:"email,omitempty" tf:"email,omitempty"`

// only subaccount. Changing this forces a new resource.
// Whether this is a host-only subaccount. Changing this forces a new resource.
HostOnly *bool `json:"hostOnly,omitempty" tf:"host_only,omitempty"`

// only, never returned by API. Changing this forces a new resource. Note: after import, this field will be empty in state since the API does not return passwords.
// Password for the subaccount. Write-only, never returned by API. Changing this forces a new resource. Note: after import, this field will be empty in state since the API does not return passwords.
PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

// (String) Username for the subaccount. Changing this forces a new resource.
// Username for the subaccount. Changing this forces a new resource.
Username *string `json:"username,omitempty" tf:"username,omitempty"`
}


type SubaccountObservation struct {


// (String) Email address for the subaccount. Changing this forces a new resource.
// Email address for the subaccount. Changing this forces a new resource.
Email *string `json:"email,omitempty" tf:"email,omitempty"`

// only subaccount. Changing this forces a new resource.
// Whether this is a host-only subaccount. Changing this forces a new resource.
HostOnly *bool `json:"hostOnly,omitempty" tf:"host_only,omitempty"`

// (String) Unique numeric identifier of the subaccount.
ID *string `json:"id,omitempty" tf:"id,omitempty"`

// (String) Username for the subaccount. Changing this forces a new resource.
// Username for the subaccount. Changing this forces a new resource.
Username *string `json:"username,omitempty" tf:"username,omitempty"`
}


type SubaccountParameters struct {


// (String) Email address for the subaccount. Changing this forces a new resource.
// Email address for the subaccount. Changing this forces a new resource.
// +kubebuilder:validation:Optional
Email *string `json:"email,omitempty" tf:"email,omitempty"`

// only subaccount. Changing this forces a new resource.
// Whether this is a host-only subaccount. Changing this forces a new resource.
// +kubebuilder:validation:Optional
HostOnly *bool `json:"hostOnly,omitempty" tf:"host_only,omitempty"`

// only, never returned by API. Changing this forces a new resource. Note: after import, this field will be empty in state since the API does not return passwords.
// Password for the subaccount. Write-only, never returned by API. Changing this forces a new resource. Note: after import, this field will be empty in state since the API does not return passwords.
// +kubebuilder:validation:Optional
PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

// (String) Username for the subaccount. Changing this forces a new resource.
// Username for the subaccount. Changing this forces a new resource.
// +kubebuilder:validation:Optional
Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// SubaccountSpec defines the desired state of Subaccount
type SubaccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider       SubaccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider       SubaccountInitParameters `json:"initProvider,omitempty"`
}

// SubaccountStatus defines the observed state of Subaccount.
type SubaccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider          SubaccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion


// Subaccount is the Schema for the Subaccounts API. Manages a Vast.ai subaccount.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vastai}
type Subaccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec              SubaccountSpec   `json:"spec"`
	Status            SubaccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubaccountList contains a list of Subaccounts
type SubaccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Subaccount `json:"items"`
}

// Repository type metadata.
var (
	Subaccount_Kind             = "Subaccount"
	Subaccount_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Subaccount_Kind}.String()
	Subaccount_KindAPIVersion   = Subaccount_Kind + "." + CRDGroupVersion.String()
	Subaccount_GroupVersionKind = CRDGroupVersion.WithKind(Subaccount_Kind)
)

func init() {
	SchemeBuilder.Register(&Subaccount{}, &SubaccountList{})
}
