// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0


// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "gitlab.adva-soft.com/devopsteam/crossplane-vast.ai-provider/apis/cluster/account/v1alpha1"
v1alpha1compute "gitlab.adva-soft.com/devopsteam/crossplane-vast.ai-provider/apis/cluster/compute/v1alpha1"
v1alpha1network "gitlab.adva-soft.com/devopsteam/crossplane-vast.ai-provider/apis/cluster/network/v1alpha1"
v1alpha1storage "gitlab.adva-soft.com/devopsteam/crossplane-vast.ai-provider/apis/cluster/storage/v1alpha1"
v1alpha1cluster "gitlab.adva-soft.com/devopsteam/crossplane-vast.ai-provider/apis/cluster/v1alpha1"
v1beta1 "gitlab.adva-soft.com/devopsteam/crossplane-vast.ai-provider/apis/cluster/v1beta1"

)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1compute.SchemeBuilder.AddToScheme,
		v1alpha1network.SchemeBuilder.AddToScheme,
		v1alpha1storage.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
