// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0


// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"

)




type OverlayMemberInitParameters struct {


// (String) ID of the instance to join to the overlay.
// ID of the instance to join to the overlay.
InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

// (String) Name of the overlay to join.
// Name of the overlay to join.
OverlayName *string `json:"overlayName,omitempty" tf:"overlay_name,omitempty"`
}


type OverlayMemberObservation struct {


// (String) Composite ID: overlay_id/instance_id.
ID *string `json:"id,omitempty" tf:"id,omitempty"`

// (String) ID of the instance to join to the overlay.
// ID of the instance to join to the overlay.
InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

// (String) ID of the overlay.
// ID of the overlay.
OverlayID *string `json:"overlayId,omitempty" tf:"overlay_id,omitempty"`

// (String) Name of the overlay to join.
// Name of the overlay to join.
OverlayName *string `json:"overlayName,omitempty" tf:"overlay_name,omitempty"`
}


type OverlayMemberParameters struct {


// (String) ID of the instance to join to the overlay.
// ID of the instance to join to the overlay.
// +kubebuilder:validation:Optional
InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

// (String) Name of the overlay to join.
// Name of the overlay to join.
// +kubebuilder:validation:Optional
OverlayName *string `json:"overlayName,omitempty" tf:"overlay_name,omitempty"`
}

// OverlayMemberSpec defines the desired state of OverlayMember
type OverlayMemberSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider       OverlayMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider       OverlayMemberInitParameters `json:"initProvider,omitempty"`
}

// OverlayMemberStatus defines the observed state of OverlayMember.
type OverlayMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider          OverlayMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion


// OverlayMember is the Schema for the OverlayMembers API. Joins an instance to a Vast.ai overlay network.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vastai}
type OverlayMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instanceId) || (has(self.initProvider) && has(self.initProvider.instanceId))",message="spec.forProvider.instanceId is a required parameter"
// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.overlayName) || (has(self.initProvider) && has(self.initProvider.overlayName))",message="spec.forProvider.overlayName is a required parameter"
	Spec              OverlayMemberSpec   `json:"spec"`
	Status            OverlayMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OverlayMemberList contains a list of OverlayMembers
type OverlayMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OverlayMember `json:"items"`
}

// Repository type metadata.
var (
	OverlayMember_Kind             = "OverlayMember"
	OverlayMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OverlayMember_Kind}.String()
	OverlayMember_KindAPIVersion   = OverlayMember_Kind + "." + CRDGroupVersion.String()
	OverlayMember_GroupVersionKind = CRDGroupVersion.WithKind(OverlayMember_Kind)
)

func init() {
	SchemeBuilder.Register(&OverlayMember{}, &OverlayMemberList{})
}
