// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type EndpointInitParameters struct {

	// (Number) Cold capacity as multiple of hot capacity (default: 2.5).
	// Cold capacity as multiple of hot capacity (default: 2.5).
	ColdMult *float64 `json:"coldMult,omitempty" tf:"cold_mult,omitempty"`

	// (Number) Minimum cold workers when no load (default: 5).
	// Minimum cold workers when no load (default: 5).
	ColdWorkers *float64 `json:"coldWorkers,omitempty" tf:"cold_workers,omitempty"`

	// (String) Name of the serverless endpoint.
	// Name of the serverless endpoint.
	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	// (String) Endpoint runtime state (active, suspended, stopped). New endpoints start as active.
	// Endpoint runtime state (active, suspended, stopped). New endpoints start as active.
	EndpointState *string `json:"endpointState,omitempty" tf:"endpoint_state,omitempty"`

	// (Number) Maximum workers the endpoint can have (default: 20).
	// Maximum workers the endpoint can have (default: 20).
	MaxWorkers *float64 `json:"maxWorkers,omitempty" tf:"max_workers,omitempty"`

	// (Number) Minimum floor load allowing cold workers (default: 0).
	// Minimum floor load allowing cold workers (default: 0).
	MinColdLoad *float64 `json:"minColdLoad,omitempty" tf:"min_cold_load,omitempty"`

	// (Number) Minimum floor load in perf units/s (default: 0).
	// Minimum floor load in perf units/s (default: 0).
	MinLoad *float64 `json:"minLoad,omitempty" tf:"min_load,omitempty"`

	// (Number) Target capacity utilization fraction (default: 0.9).
	// Target capacity utilization fraction (default: 0.9).
	TargetUtil *float64 `json:"targetUtil,omitempty" tf:"target_util,omitempty"`
}

type EndpointObservation struct {

	// (Number) Cold capacity as multiple of hot capacity (default: 2.5).
	// Cold capacity as multiple of hot capacity (default: 2.5).
	ColdMult *float64 `json:"coldMult,omitempty" tf:"cold_mult,omitempty"`

	// (Number) Minimum cold workers when no load (default: 5).
	// Minimum cold workers when no load (default: 5).
	ColdWorkers *float64 `json:"coldWorkers,omitempty" tf:"cold_workers,omitempty"`

	// (String) Name of the serverless endpoint.
	// Name of the serverless endpoint.
	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	// (String) Endpoint runtime state (active, suspended, stopped). New endpoints start as active.
	// Endpoint runtime state (active, suspended, stopped). New endpoints start as active.
	EndpointState *string `json:"endpointState,omitempty" tf:"endpoint_state,omitempty"`

	// (String) Endpoint ID. Used as the primary identifier for reads, updates, deletes, and imports.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Maximum workers the endpoint can have (default: 20).
	// Maximum workers the endpoint can have (default: 20).
	MaxWorkers *float64 `json:"maxWorkers,omitempty" tf:"max_workers,omitempty"`

	// (Number) Minimum floor load allowing cold workers (default: 0).
	// Minimum floor load allowing cold workers (default: 0).
	MinColdLoad *float64 `json:"minColdLoad,omitempty" tf:"min_cold_load,omitempty"`

	// (Number) Minimum floor load in perf units/s (default: 0).
	// Minimum floor load in perf units/s (default: 0).
	MinLoad *float64 `json:"minLoad,omitempty" tf:"min_load,omitempty"`

	// (Number) Target capacity utilization fraction (default: 0.9).
	// Target capacity utilization fraction (default: 0.9).
	TargetUtil *float64 `json:"targetUtil,omitempty" tf:"target_util,omitempty"`
}

type EndpointParameters struct {

	// (Number) Cold capacity as multiple of hot capacity (default: 2.5).
	// Cold capacity as multiple of hot capacity (default: 2.5).
	// +kubebuilder:validation:Optional
	ColdMult *float64 `json:"coldMult,omitempty" tf:"cold_mult,omitempty"`

	// (Number) Minimum cold workers when no load (default: 5).
	// Minimum cold workers when no load (default: 5).
	// +kubebuilder:validation:Optional
	ColdWorkers *float64 `json:"coldWorkers,omitempty" tf:"cold_workers,omitempty"`

	// (String) Name of the serverless endpoint.
	// Name of the serverless endpoint.
	// +kubebuilder:validation:Optional
	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	// (String) Endpoint runtime state (active, suspended, stopped). New endpoints start as active.
	// Endpoint runtime state (active, suspended, stopped). New endpoints start as active.
	// +kubebuilder:validation:Optional
	EndpointState *string `json:"endpointState,omitempty" tf:"endpoint_state,omitempty"`

	// (Number) Maximum workers the endpoint can have (default: 20).
	// Maximum workers the endpoint can have (default: 20).
	// +kubebuilder:validation:Optional
	MaxWorkers *float64 `json:"maxWorkers,omitempty" tf:"max_workers,omitempty"`

	// (Number) Minimum floor load allowing cold workers (default: 0).
	// Minimum floor load allowing cold workers (default: 0).
	// +kubebuilder:validation:Optional
	MinColdLoad *float64 `json:"minColdLoad,omitempty" tf:"min_cold_load,omitempty"`

	// (Number) Minimum floor load in perf units/s (default: 0).
	// Minimum floor load in perf units/s (default: 0).
	// +kubebuilder:validation:Optional
	MinLoad *float64 `json:"minLoad,omitempty" tf:"min_load,omitempty"`

	// (Number) Target capacity utilization fraction (default: 0.9).
	// Target capacity utilization fraction (default: 0.9).
	// +kubebuilder:validation:Optional
	TargetUtil *float64 `json:"targetUtil,omitempty" tf:"target_util,omitempty"`
}

// EndpointSpec defines the desired state of Endpoint
type EndpointSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EndpointParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EndpointInitParameters `json:"initProvider,omitempty"`
}

// EndpointStatus defines the observed state of Endpoint.
type EndpointStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EndpointObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Endpoint is the Schema for the Endpoints API. Manages a Vast.ai serverless endpoint.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vastai}
type Endpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endpointName) || (has(self.initProvider) && has(self.initProvider.endpointName))",message="spec.forProvider.endpointName is a required parameter"
	Spec   EndpointSpec   `json:"spec"`
	Status EndpointStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EndpointList contains a list of Endpoints
type EndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Endpoint `json:"items"`
}

// Repository type metadata.
var (
	Endpoint_Kind             = "Endpoint"
	Endpoint_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Endpoint_Kind}.String()
	Endpoint_KindAPIVersion   = Endpoint_Kind + "." + CRDGroupVersion.String()
	Endpoint_GroupVersionKind = CRDGroupVersion.WithKind(Endpoint_Kind)
)

func init() {
	SchemeBuilder.Register(&Endpoint{}, &EndpointList{})
}
