// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type WorkerGroupInitParameters struct {

	// (Number) Minimum cold workers for this worker group.
	// Minimum cold workers for this worker group.
	ColdWorkers *float64 `json:"coldWorkers,omitempty" tf:"cold_workers,omitempty"`

	// (Number) ID of the parent endpoint this worker group belongs to. Changing this forces a new resource.
	// ID of the parent endpoint this worker group belongs to. Changing this forces a new resource.
	EndpointID *float64 `json:"endpointId,omitempty" tf:"endpoint_id,omitempty"`

	// (String) Name of the parent endpoint (computed from endpoint_id if not set).
	// Name of the parent endpoint (computed from endpoint_id if not set).
	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	// (Number) Estimated GPU RAM requirement in GB.
	// Estimated GPU RAM requirement in GB.
	GpuRAM *float64 `json:"gpuRam,omitempty" tf:"gpu_ram,omitempty"`

	// (String) Instance launch arguments string.
	// Instance launch arguments string.
	LaunchArgs *string `json:"launchArgs,omitempty" tf:"launch_args,omitempty"`

	// (String) Offer search filter string (e.g. 'gpu_ram>=23 num_gpus=2 gpu_name=RTX_4090'). The API may apply default filters (verified=True rentable=True rented=False).
	// Offer search filter string (e.g. 'gpu_ram>=23 num_gpus=2 gpu_name=RTX_4090'). The API may apply default filters (verified=True rentable=True rented=False).
	SearchParams *string `json:"searchParams,omitempty" tf:"search_params,omitempty"`

	// (String) Template hash for worker instances. Either template_hash or template_id must be provided.
	// Template hash for worker instances. Either template_hash or template_id must be provided.
	TemplateHash *string `json:"templateHash,omitempty" tf:"template_hash,omitempty"`

	// (Number) Numeric template ID for worker instances. Either template_hash or template_id must be provided.
	// Numeric template ID for worker instances. Either template_hash or template_id must be provided.
	TemplateID *float64 `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// (Number) Number of workers for initial performance estimate (default: 3).
	// Number of workers for initial performance estimate (default: 3).
	TestWorkers *float64 `json:"testWorkers,omitempty" tf:"test_workers,omitempty"`
}

type WorkerGroupObservation struct {

	// (Number) Minimum cold workers for this worker group.
	// Minimum cold workers for this worker group.
	ColdWorkers *float64 `json:"coldWorkers,omitempty" tf:"cold_workers,omitempty"`

	// (Number) ID of the parent endpoint this worker group belongs to. Changing this forces a new resource.
	// ID of the parent endpoint this worker group belongs to. Changing this forces a new resource.
	EndpointID *float64 `json:"endpointId,omitempty" tf:"endpoint_id,omitempty"`

	// (String) Name of the parent endpoint (computed from endpoint_id if not set).
	// Name of the parent endpoint (computed from endpoint_id if not set).
	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	// (Number) Estimated GPU RAM requirement in GB.
	// Estimated GPU RAM requirement in GB.
	GpuRAM *float64 `json:"gpuRam,omitempty" tf:"gpu_ram,omitempty"`

	// (String) Worker group ID. Used as the primary identifier for reads, updates, deletes, and imports.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Instance launch arguments string.
	// Instance launch arguments string.
	LaunchArgs *string `json:"launchArgs,omitempty" tf:"launch_args,omitempty"`

	// (String) Offer search filter string (e.g. 'gpu_ram>=23 num_gpus=2 gpu_name=RTX_4090'). The API may apply default filters (verified=True rentable=True rented=False).
	// Offer search filter string (e.g. 'gpu_ram>=23 num_gpus=2 gpu_name=RTX_4090'). The API may apply default filters (verified=True rentable=True rented=False).
	SearchParams *string `json:"searchParams,omitempty" tf:"search_params,omitempty"`

	// (String) Template hash for worker instances. Either template_hash or template_id must be provided.
	// Template hash for worker instances. Either template_hash or template_id must be provided.
	TemplateHash *string `json:"templateHash,omitempty" tf:"template_hash,omitempty"`

	// (Number) Numeric template ID for worker instances. Either template_hash or template_id must be provided.
	// Numeric template ID for worker instances. Either template_hash or template_id must be provided.
	TemplateID *float64 `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// (Number) Number of workers for initial performance estimate (default: 3).
	// Number of workers for initial performance estimate (default: 3).
	TestWorkers *float64 `json:"testWorkers,omitempty" tf:"test_workers,omitempty"`
}

type WorkerGroupParameters struct {

	// (Number) Minimum cold workers for this worker group.
	// Minimum cold workers for this worker group.
	// +kubebuilder:validation:Optional
	ColdWorkers *float64 `json:"coldWorkers,omitempty" tf:"cold_workers,omitempty"`

	// (Number) ID of the parent endpoint this worker group belongs to. Changing this forces a new resource.
	// ID of the parent endpoint this worker group belongs to. Changing this forces a new resource.
	// +kubebuilder:validation:Optional
	EndpointID *float64 `json:"endpointId,omitempty" tf:"endpoint_id,omitempty"`

	// (String) Name of the parent endpoint (computed from endpoint_id if not set).
	// Name of the parent endpoint (computed from endpoint_id if not set).
	// +kubebuilder:validation:Optional
	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	// (Number) Estimated GPU RAM requirement in GB.
	// Estimated GPU RAM requirement in GB.
	// +kubebuilder:validation:Optional
	GpuRAM *float64 `json:"gpuRam,omitempty" tf:"gpu_ram,omitempty"`

	// (String) Instance launch arguments string.
	// Instance launch arguments string.
	// +kubebuilder:validation:Optional
	LaunchArgs *string `json:"launchArgs,omitempty" tf:"launch_args,omitempty"`

	// (String) Offer search filter string (e.g. 'gpu_ram>=23 num_gpus=2 gpu_name=RTX_4090'). The API may apply default filters (verified=True rentable=True rented=False).
	// Offer search filter string (e.g. 'gpu_ram>=23 num_gpus=2 gpu_name=RTX_4090'). The API may apply default filters (verified=True rentable=True rented=False).
	// +kubebuilder:validation:Optional
	SearchParams *string `json:"searchParams,omitempty" tf:"search_params,omitempty"`

	// (String) Template hash for worker instances. Either template_hash or template_id must be provided.
	// Template hash for worker instances. Either template_hash or template_id must be provided.
	// +kubebuilder:validation:Optional
	TemplateHash *string `json:"templateHash,omitempty" tf:"template_hash,omitempty"`

	// (Number) Numeric template ID for worker instances. Either template_hash or template_id must be provided.
	// Numeric template ID for worker instances. Either template_hash or template_id must be provided.
	// +kubebuilder:validation:Optional
	TemplateID *float64 `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// (Number) Number of workers for initial performance estimate (default: 3).
	// Number of workers for initial performance estimate (default: 3).
	// +kubebuilder:validation:Optional
	TestWorkers *float64 `json:"testWorkers,omitempty" tf:"test_workers,omitempty"`
}

// WorkerGroupSpec defines the desired state of WorkerGroup
type WorkerGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WorkerGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkerGroupInitParameters `json:"initProvider,omitempty"`
}

// WorkerGroupStatus defines the observed state of WorkerGroup.
type WorkerGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WorkerGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkerGroup is the Schema for the WorkerGroups API. Manages a Vast.ai worker group.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vastai}
type WorkerGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endpointId) || (has(self.initProvider) && has(self.initProvider.endpointId))",message="spec.forProvider.endpointId is a required parameter"
	Spec   WorkerGroupSpec   `json:"spec"`
	Status WorkerGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkerGroupList contains a list of WorkerGroups
type WorkerGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkerGroup `json:"items"`
}

// Repository type metadata.
var (
	WorkerGroup_Kind             = "WorkerGroup"
	WorkerGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkerGroup_Kind}.String()
	WorkerGroup_KindAPIVersion   = WorkerGroup_Kind + "." + CRDGroupVersion.String()
	WorkerGroup_GroupVersionKind = CRDGroupVersion.WithKind(WorkerGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkerGroup{}, &WorkerGroupList{})
}
